version: 2.1

aliases:
  - &ci_executor
    working_directory: ~/worship_mate/
    shell: /bin/bash -eux -o pipefail
  - &docker_node_image circleci/node:12.8.1-stretch

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  docker_node:
    <<: *ci_executor
    docker:
      - image: *docker_node_image

  docker_node_postgres:
    <<: *ci_executor
    docker:
      - image: *docker_node_image
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_DB: pg_fusion_test
    environment:
      PGUSER: postgres
      PGDATABASE: pg_fusion_test

commands:
  install_yarn_deps:
    steps:
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install external dependencies
          command: yarn install --immutable
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache/

jobs:
  build_and_test:
    executor: docker_node_postgres

    steps:
      - checkout
      - install_yarn_deps
      - run: yarn typecheck
      - run: yarn build
      - run: yarn test --coverage
      - codecov/upload:
          file: coverage/lcov.info

      - run: yarn test:e2e --coverage
      - codecov/upload:
          file: coverage/lcov.info

  lint:
    executor: docker_node

    steps:
      - checkout
      - install_yarn_deps
      - run:
          name: Install pre-commit
          command: curl https://pre-commit.com/install-local.py | python -
      - run:
          name: Run pre-commit
          command: pre-commit run --all-files

workflows:
  version: 2

  build_and_test:
    jobs:
      - build_and_test
      - lint
