version: 2.1

aliases:
  - &ci_executor
    working_directory: ~/pg_fusion/
    shell: /bin/bash -eux -o pipefail
  - &docker_node_image circleci/node:12.8.1-stretch

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  docker_node:
    <<: *ci_executor
    docker:
      - image: *docker_node_image

  docker_node_postgres:
    <<: *ci_executor
    docker:
      - image: *docker_node_image
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_DB: pg_fusion_test
    environment:
      PGUSER: postgres
      PGDATABASE: pg_fusion_test

  docker_ruby:
    <<: *ci_executor
    docker:
      - image: circleci/ruby:2.7.1

commands:
  install_yarn_deps:
    steps:
      - restore_cache:
          key: v2-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install external dependencies
          command: yarn install --immutable
      - save_cache:
          key: v2-yarn-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache/

jobs:
  build_and_test:
    executor: docker_node_postgres
    steps:
      - checkout
      - install_yarn_deps

      - run: yarn typecheck
      - run: yarn build

      - run: yarn test --coverage
      - codecov/upload:
          file: coverage/lcov.info
      - run: yarn test:e2e --coverage
      - codecov/upload:
          file: coverage/lcov.info

      - run:
          name: Bundle package
          command: |
            mkdir -p .ci
            yarn pack -o .ci/%s-%v.tgz
      - store_artifacts:
          path: .ci/
          destination: .

  lint:
    executor: docker_node
    steps:
      - checkout
      - install_yarn_deps
      - run:
          name: Install pre-commit
          command: curl https://pre-commit.com/install-local.py | python -
      - run:
          name: Run pre-commit
          command: pre-commit run --all-files

  docs:
    executor: docker_ruby
    steps:
      - checkout

      - restore_cache:
          key: v1-rubygems-{{ checksum "docs/Gemfile.lock" }}
      - run:
          command: bundle config set path vendor/bundle
          working_directory: docs/
      - run:
          command: bundle install
          working_directory: docs/
      - save_cache:
          key: v1-rubygems-{{ checksum "docs/Gemfile.lock" }}
          paths:
            - docs/vendor/bundle

      - run:
          command: bundle exec jekyll build
          working_directory: docs/
      - run:
          name: Bundle built site
          command: tar czf jekyll-docs.tar.gz _site
          working_directory: docs/
      - store_artifacts:
          path: docs/jekyll-docs.tar.gz

  deploy:
    executor: docker_node
    steps:
      - checkout
      - run:
          name: Set NPM token
          command: yarn config set npmAuthToken "${NPM_TOKEN}"
      - run:
          name: Publish package
          command: yarn npm publish --tolerate-republish

workflows:
  version: 2
  pg-fusion-ci:
    jobs:
      - build_and_test
      - lint
      - docs
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build_and_test
            - lint
            - docs
